### ISSUE TITLE
多个页面崩溃

### ISSUE THREAD

**Issue by morning-tan** [websoft9op/recruitment#23]
![image](https://github.com/Websoft9/handbook/assets/54173243/bf71de24-e5a0-4857-b1e0-7617df6c74ef)

https://support.websoft9.com/handbook/company/purpose/  组织-企业宗旨
https://support.websoft9.com/handbook/company/govern     组织-公司治理
https://support.websoft9.com/handbook/engineering/philosophy     工程-工程哲学
https://support.websoft9.com/handbook/sales/csm    销售-客户成功
https://support.websoft9.com/handbook/sales/service/     销售-专业服务
https://support.websoft9.com/handbook/legal/tob    法务-业务经营

**Comment by chendelin1982** [comment]
fixed.
solution: upgrade docusaurus and theme-mermaid
